/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ctmonsalve' at '12/28/15 6:10 PM' with Gradle 2.6
 *
 * @author ctmonsalve, @date 12/28/15 6:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
